# Generated by Django 4.2.7 on 2023-11-18 10:18

import apps.customer_company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customercompany',
            managers=[
                ('objects', apps.customer_company.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customercompany',
            name='activation_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customercompany',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customercompany',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
