# Generated by Django 4.2.7 on 2023-11-18 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customer_company', '0002_alter_customercompany_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercompany',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customercompany',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customer_company_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, error_messages={'add': 'You cannot add permission directly to users. Use groups instead.', 'remove': 'You cannot remove permission directly from users. Use groups instead.'}, help_text='Specific permissions for this user.', related_name='customer_company_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
