# Generated by Django 4.2.7 on 2023-11-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_freelancer_avatar_alter_freelancer_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
