# Generated by Django 4.2.7 on 2023-11-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_freelancer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profession',
            field=models.CharField(default='self-taught', max_length=90),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
