# Generated by Django 4.2.7 on 2023-11-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_alter_freelancer_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='username',
        ),
    ]
