# Generated by Django 4.2.7 on 2023-11-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_remove_freelancer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
