# Generated by Django 4.2.7 on 2023-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('freelancer', '0006_freelancer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='freelancer_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, error_messages={'add': 'You cannot add permission directly to users. Use groups instead.', 'remove': 'You cannot remove permission directly from users. Use groups instead.'}, help_text='Specific permissions for this user.', related_name='freelancer_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
