# Generated by Django 4.2.7 on 2023-11-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('in_process', 'In Process'), ('completed', 'Completed')], default='opened', max_length=20),
        ),
    ]
