# Generated by Django 4.2.7 on 2023-11-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='freelancer.freelancer'),
        ),
    ]
